version: '2.1'

services:
  shiatsu_db:
    build: ./mysql
    volumes:
      - ./container_data/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  shiatsu_php:
    build: ./php
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./container_data/log:/var/log/apache2
      - ./html:/var/www/html
    depends_on:
      shiatsu_db:
        condition: service_healthy
    command: bash -c "echo 'This command is run each time the container is started' && apache2-foreground"
    tty: true
  shiatsu_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shiatsu_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    volumes:
      - /sessions
    depends_on:
      - shiatsu_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      #volumes:
  shiatsu_phpmyadmin_proxy:  
    image: nginx:stable
    volumes:
      - ./nginx_phpmyadmin/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_phpmyadmin/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - shiatsu_phpmyadmin
    ports:
      - 8080:80
