version: '2.1'

services:
  db:
    build: ./mysql
    volumes:
      - ./container_data/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  php:
    build: ./php
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./container_data/log:/var/log/apache2
      - ./html:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "echo 'This command is run each time the container is started' && apache2-foreground"
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      #volumes:
    #db_data:
